package resources

import "time"

type AutoGenerated struct {
	Event        Event        `json:"event"`
	CreatedAt    time.Time    `json:"created_at"`
	ID           string       `json:"id"`
	DeliveryInfo DeliveryInfo `json:"delivery_info"`
	Trigger      Trigger      `json:"trigger"`
	Table        Table        `json:"table"`
}
type SessionVariables struct {
	XHasuraRole string `json:"x-hasura-role"`
}
type New struct {
	Title string `json:"title"`
	Body  string `json:"body"`
	Count int    `json:"count"`
}
type Data struct {
	Old interface{} `json:"old"`
	New New         `json:"new"`
}
type Event struct {
	SessionVariables SessionVariables `json:"session_variables"`
	Op               string           `json:"op"`
	Data             Data             `json:"data"`
}
type DeliveryInfo struct {
	MaxRetries   int `json:"max_retries"`
	CurrentRetry int `json:"current_retry"`
}
type Trigger struct {
	Name string `json:"name"`
}
type Table struct {
	Schema string `json:"schema"`
	Name   string `json:"name"`
}
