package handler

import (
	"encoding/json"
	"fmt"
	repository "go_microservice/repository"
	"go_microservice/resources"
	"io/ioutil"
	"log"

	"github.com/gin-gonic/gin"
)

// HandlePost parses request into services.Article struct
func HandlePost() gin.HandlerFunc {
	return func(c *gin.Context) {
		var a resources.AutoGenerated
		b, err := ioutil.ReadAll(c.Request.Body)
		if err != nil {
			log.Fatal(err)
		}
		err = json.Unmarshal(b, &a)
		if err != nil {
			log.Fatal(err)
		}
		handleCount(a.Event.Data.New)
	}
}

func handleCount(a resources.New) {
	repo := repository.New()
	repo.Add(a)
	fmt.Println(repo.GetAll())
}
